### ISSUE TITLE
Add local and global rotation for sprite and mesh

### ISSUE THREAD

**Issue by h4570** [h4570/tyra#10]
@Foxar please describe the feature if you could.

**Comment by Foxar** [comment]
The behavior is well described here:
https://www.youtube.com/watch?v=q0jgqeS_ACM&ab_channel=Udacity

As of now, tyra allows only for flawed rotation of 3d models because of usage of Euler angles. This means they can only rotate around their own axes. This behavior can be noticed in the dolphin sample, in develop branch:
![0DALt3n1GV](https://user-images.githubusercontent.com/6164708/101175956-1998ff80-3646-11eb-8287-97b9a24fb0b5.gif)

Intended behavior would be that while submerging, the dolphin's tilted forwards (relative to himself), no matter what his z-rotation (yaw/heading).

**Comment by h4570** [comment]
Resolved in Tyra 2.0.0
