### ISSUE TITLE
Concentrate all method's definitions in the .cpp files of their respective class

### ISSUE THREAD

**Issue by Foxar** [h4570/tyra#32]
I'm not sure why some methods are defined within the header files while some in the cpp files of some classes. Good example is 
[mesh_frame.hpp](https://github.com/h4570/tyra/blob/d58163d75be2d6c848f4456f73cebd8a6c1a63bd/src/engine/include/models/mesh_frame.hpp)
`void setVertexFace(const u32 &t_index, const u32 &t_val) { vertexFaces[t_index] = t_val; }`
`void setSTFace(const u32 &t_index, const u32 &t_val) { stFaces[t_index] = t_val;  }`
`void setNormalFace(const u32 &t_index, const u32 &t_val) { normalFaces[t_index] = t_val; }`

I understand they are short and possibly self-explanatory from the name, but perhaps it'd be better to concentrate all definitions of a given class in one file to make finding definitions a bit easier. Need your opinion on it @h4570

**Comment by h4570** [comment]
Because I wanted to do it as **inline** https://github.com/h4570/tyra/issues/25 which (from what I know) is not possible to do in cpp file.
I don't want tell compiler to create new function for it, because we will have (and have right now) performance issue there.
But to be honest, when I saw some source codes, I see that this is pretty common approach, to describe small functionalities just in header file. But anyways I'm not a c++ expert.
